// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeLxk7Dlb9PIGD4b44mLlBLs_mh5nwAho',
    appId: '1:776709123368:web:f9d21bec30f399b4b2b41d',
    messagingSenderId: '776709123368',
    projectId: 'flowsavvy-bc9b9',
    authDomain: 'flowsavvy-bc9b9.firebaseapp.com',
    storageBucket: 'flowsavvy-bc9b9.firebasestorage.app',
    measurementId: 'G-R68ZWY3GVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZPqDK8ALVPmsLvmXIxdeR6Yyhq3bCvU',
    appId: '1:776709123368:android:2a38ccf672add91fb2b41d',
    messagingSenderId: '776709123368',
    projectId: 'flowsavvy-bc9b9',
    storageBucket: 'flowsavvy-bc9b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzt0MIRfTjlGrKo9t_SPP6DbIXmCMSCs',
    appId: '1:776709123368:ios:6d4815e963d9eeb0b2b41d',
    messagingSenderId: '776709123368',
    projectId: 'flowsavvy-bc9b9',
    storageBucket: 'flowsavvy-bc9b9.firebasestorage.app',
    iosBundleId: 'com.example.flowSavvy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApzt0MIRfTjlGrKo9t_SPP6DbIXmCMSCs',
    appId: '1:776709123368:ios:6d4815e963d9eeb0b2b41d',
    messagingSenderId: '776709123368',
    projectId: 'flowsavvy-bc9b9',
    storageBucket: 'flowsavvy-bc9b9.firebasestorage.app',
    iosBundleId: 'com.example.flowSavvy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeLxk7Dlb9PIGD4b44mLlBLs_mh5nwAho',
    appId: '1:776709123368:web:5e944c33558f4e7ab2b41d',
    messagingSenderId: '776709123368',
    projectId: 'flowsavvy-bc9b9',
    authDomain: 'flowsavvy-bc9b9.firebaseapp.com',
    storageBucket: 'flowsavvy-bc9b9.firebasestorage.app',
    measurementId: 'G-2V4QRGJHTY',
  );
}
